import React from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import data from "./coffeeStores.json";
import { useRouter } from "next/router";
import {
  StarIcon,
  ChevronLeftIcon,
  LocationMarkerIcon,
  PaperAirplaneIcon,
  GlobeIcon,
} from "@heroicons/react/solid";

export async function getStaticProps({ params }) {
  return {
    props: { post: data.find((s) => s.id == params.id) }, // will be passed to the page component as props
  };
}
export async function getStaticPaths() {
  const paths = data.map((s) => {
    return { params: { id: s.id.toString() } };
  });
  return {
    paths,
    fallback: true,
  };
}

function Id(props) {
  const router = useRouter();
  if (router.isFallback) {
    return (
      <div className="flex items-center justify-center h-screen w-screen">
        <h1 className="text-white font-extrabold text-center text-[40px]">
          loading ...
        </h1>
      </div>
    );
  }
  const onClick = () => {
    console.log("up vote");
  };
  return (
    <>
      <Head>
        <title>{props.post?.name}</title>
        <meta name="description" content="Description" />
        <meta name="keywords" content="Keywords" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col container mx-auto px-5 py-10 min-h-screen h-full">
        <Link href="/" className="" scroll={false}>
          <a className="text-blue-600 hover:text-blue-300 mb-8 font-bold">
            <ChevronLeftIcon className="w-6 inline-block" />
            back to home
          </a>
        </Link>
        <div className="grid grid-cols-1 gap-8 md:grid-cols-2 p-4 text-white text-bold  ">
          <div className="flex items-center justify-center  bg-pink-200 rounded-md bg-clip-padding backdrop-filter backdrop-blur-xl bg-opacity-60 border border-gray-200">
            <Image
              src={"/static/hero-image.png"}
              // src={props.post.imgUrl}
              alt={props.post.name}
              width={200}
              height={150}
            />
          </div>
          <div className="p-4 bg-pink-200 rounded-lg bg-clip-padding backdrop-filter backdrop-blur-xl bg-opacity-60 border border-gray-200 ">
            <h1 className="mb-8 text-pink-500 text-[26px] font-extrabold">
              {props.post?.name}
            </h1>
            <h3 className="mb-5 text-bold flex items-start ">
              <LocationMarkerIcon className="w-6 inline-block mr-2" />
              <span>{props.post?.address}</span>
            </h3>
            <h2 className="mb-5 text-bold flex items-start  ">
              <PaperAirplaneIcon className="w-6 inline-block mr-2" />
              {props.post?.neighbourhood}
            </h2>

            <a
              className=" text-bold flex items-start mb-5"
              href={props.post?.websiteUrl}
            >
              <GlobeIcon className="w-6 inline-block mr-2" />
              <span> {props.post?.websiteUrl}</span>
            </a>
            <h2 className="mb-9 text-bold flex items-start  ">
              <StarIcon className="w-6 inline-block mr-2" />1
            </h2>
            <button
              onClick={onClick}
              className="block text-[12px] font-semibold  bg-blue-800 p-2 rounded-md hover:bg-blue-500 hover:shadow-sm"
            >
              Up vote!
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
export default Id;
