import React from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import data from "./coffeeStores.json";
import { useRouter } from "next/router";

export async function getStaticProps({ params }) {
  return {
    props: { post: data.find((s) => s.id == params.id) }, // will be passed to the page component as props
  };
}
export async function getStaticPaths() {
  const paths = data.map((s) => {
    return { params: { id: s.id.toString() } };
  });
  return {
    paths,
    fallback: true,
  };
}

function Id(props) {
  const router = useRouter();
  if (router.isFallback) {
    return (
      <div className="flex items-center justify-center h-screen w-screen">
        <h1 className="text-white font-extrabold text-center text-[40px]">
          loading ...
        </h1>
      </div>
    );
  }
  return (
    <>
      <Head>
        <title>{props.post?.name}</title>
        <meta name="description" content="Description" />
        <meta name="keywords" content="Keywords" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col container mx-auto p-5 min-h-screen h-full">
        <Link href="/" className="" scroll={false}>
          <a className="text-blue-600 hover:text-blue-300 mb-8 font-bold">
            back to home
          </a>
        </Link>
        <div className="flex  flex-col md:flex-row md:w-[500px] p-4 text-white text-bold rounded-md  opacity-80 shadow-xl bg-pink-300">
          <div className="p-4  rounded-lg">
            <h1 className="mb-2 text-pink-500 text-[26px] font-extrabold">
              {props.post?.name}
            </h1>
            <h2 className="mb-2 text-bold "> {props.post?.neighbourhood}</h2>
            <h3 className="mb-5 text-bold "> {props.post?.address}</h3>
            <a
              className=" text-blue-600 hover:text-blue-300 font-bold"
              href={props.post?.address}
            >
              Go to website >
            </a>
          </div>
          <div className="flex items-center justify-center m-3 bg-white rounded-md">
            <Image
              src={"/static/hero-image.png"}
              alt={props.name}
              width={200}
              height={150}
            />
          </div>
        </div>
      </div>
    </>
  );
}
export default Id;
