import Head from "next/head";
import Banner from "components/elements/banner/index";
import Image from "next/image";
import { Heading, Card } from "components/elements";
import data from "./coffee-store/coffeeStores.json";
import { loadGetInitialProps } from "next/dist/shared/lib/utils";
export async function getStaticProps() {
  return {
    props: { post: data },
  };
}
export default function Home(props) {
  const onClickHandler = () => {
    console.log("banner btn clicked");
    const options = {method: 'GET', headers: {Accept: 'application/json'}};

    fetch('https://api.foursquare.com/v3/venues/search?query=coffee&ll=43.6%2C%20-79.3&v=20220122&client_id=AYTM0VOTYHW2JLF3WI21MBD12TXXH0HYNXEBZIMFX51HYPDN&client_secret=YPRLGRUEU5NITT2D3VNMYUER2BS54VFG32VQPIBFU01A0ZLU', options)
      .then(response => response.json())
      .then(response => console.log(response))
      .catch(err => console.error(err));}
  return (
    <>
      <Head>
        <title>Coffee Connoissumer</title>
        <meta name="description" content="Description" />
        <meta name="keywords" content="Keywords" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col container mx-auto p-5 min-h-screen h-full">
        <Banner onClick={onClickHandler} bottonText={"View stores nearby"} />
        <div className="absolute top-20 right-20 z-1">
          <Image
            src="/static/hero-image.png"
            height={200}
            width={250}
            alt="coffee"
          />
        </div>
        <Heading title="Toronto stores" />
        <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-10 px-5">
          {props.post &&
            data.map((c) => (
              <Card key={c.id} name={c.name} to={c.id} imageURL={c.imgUrl} />
            ))}
        </div>
      </main>
    </>
  );
}
